---
- name: Build Username
  set_fact:
    guac_user: "{{ student.batch_id }}-{{ student.student_id }}"

- name: Disable User
  uri:
    url: "{{ guac_url }}/api/session/data/{{ datasource }}/users/{{ guac_user }}?token={{ token }}"
    method: PUT
    body_format: json
    body:
      username: "{{ guac_user }}"
      attributes:
        disabled: "true"