---
- name: Create Report Directory
  file:
    path: "{{ report_dir }}"
    state: directory

- name: Save Credentials
  lineinfile:
    path: "{{ report_dir }}/{{ batch_id }}.csv"
    create: true
    line: "{{ guac_user }},{{ guac_password }},{{ student.vm_ip }}"